language: python
python:
  - "2.7"
sudo: required
services:
- docker
# command to install dependencies
before_install:
    - pgrep -af docker
    - dpkg -l | grep -i docker
    - pip install -U pip setuptools
    - env
install:
    - pip install -r requirements.txt
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker
    - curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname
      -s`-`uname -m` > docker-compose
    - sudo install -m 775 docker-compose /usr/local/bin
# command to run tests
script: bin/do-travis-build
