language: python
python:
  - "3.6"
sudo: required
services:
- docker
# command to install dependencies
before_install:
    - pip install -U pip setuptools
install:
    - pip install -r requirements.txt
    - npm install
# command to run tests
script: bin/do-travis-build
