dist: bionic
sudo: required
env:
  public_hostname: nomsbook.com

language: python
python:
  - "3.7"

before_install:
- pip install -U pip setuptools

install:
- pip install -r requirements.txt
- pip install .[dev]
- npm install

script:
- . bin/ci-functions
- eslint .
- karma start
- tox -e travis

after_success:
- . bin/ci-functions

- ( if-release-tag && ! if-master ) && whisk cloudform --changeset nomsite
# TODO - remove if-master after we are live!
- ( if-master ) && whisk cloudform --changeset nomsite
