language: python
python:
  - "3.7"
dist: bionic
sudo: required

before_install:
    - pip install -U pip setuptools

install:
    - pip install -r requirements.txt
    - pip install .[dev]
    - npm install


script:
- bin/do-travis-build
