language: python
python:
  - "3.7"
dist: bionic
sudo: required

job:
  include:
    - stage: test
      before_install:
      - echo "------- before_install -----------------------------------------------------------------------------"
      - pip install -U pip setuptools

      install:
      - echo "------- install -----------------------------------------------------------------------------"
      - pip install -r requirements.txt
      - pip install .[dev]
      - npm install

      script:
      - echo "------- script -----------------------------------------------------------------------------"
      - . bin/ci-functions
      ## - eslint . && echo "eslint ok 👌"
      ## - karma start
      - tox -e travis

    ## # TODO - remove this after we are live!
    ## - stage: deploy
    ##   if: branch = master
    ##   env:
    ##     public_hostname: nomsbook.com
    ##   script:
    ##   - . bin/ci-functions
    ##   - whisk cloudform --changeset nomsite

    ## - stage: deploy
    ##   if: tag =~ /^(release|devbuild)-/
    ##   env:
    ##     public_hostname: nomsbook.com
    ##   script:
    ##   - . bin/ci-functions
    ##   - whisk cloudform --changeset nomsite
