language: python
python:
  - "3.7"
dist: bionic
sudo: required

before_install:
    - pip install -U pip setuptools

install:
    - pip install -r requirements.txt
    - pip install .[dev]
    - npm install

stages:
- test
- deploy

job:
  include:
    - stage: test
      script:
      - . bin/ci-functions
      - eslint . && echo "eslint ok 👌"
      - karma start
      - tox -e travis

    - stage: deploy
      # TODO - remove this after we are live!
      if: branch = master
      env:
        public_hostname: nomsbook.com
      script:
      - . bin/ci-functions
      - whisk cloudform --changeset nomsite

    - stage: deploy
      if: tag =~ /^(release|devbuild)-/
      env:
        public_hostname: nomsbook.com
      script:
      - . bin/ci-functions
      - whisk cloudform --changeset nomsite
