version: '3'
services:
    noms-main:
        image: "corydodt/noms-main:latest"
        env_file: ../env
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - noms-src:/opt/Noms
        stdin_open: true
        tty: true

    mongo:
        image: mongo:3.4


volumes:
    noms-src:
        external: true