version: '3'
services:
    noms-base:
        image: "corydodt/noms-base:latest"
        env_file: ../env
        ports:
            - "8080:8080"
        links:
            - mongo
        depends_on:
            - mongo
        stdin_open: true
        tty: true

    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
