version: '3'
services:
    noms-src:
        build:
            context: ..
            dockerfile: deployment/noms-src/Dockerfile
        image: "corydodt/noms-src:${NOMS_VERSION}"
        volumes:
            - noms-src:/opt/Noms

    noms-main:
        build:
            context: ..
            dockerfile: deployment/noms-main/Dockerfile
        image: "corydodt/noms-main:${NOMS_VERSION}"
        command: "circus.ini"
        env_file: ../build/env
        ports:
            - 8080:8080
        links:
            - mongo
            - noms-src
        depends_on:
            - mongo
            - noms-src
        volumes:
            - noms-src:/opt/Noms

    mongo:
        image: mongo

    nginx-letsencrypt-s3:
        build:
            context: ..
            dockerfile: deployment/nginx-letsencrypt-s3/Dockerfile
        image: "corydodt/nginx-letsencrypt-s3:${NOMS_VERSION}"
        command: "sleep 600"
        env_file: 
            - ../build/env

volumes:
    noms-src: {}
